### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by apu52**
Hello Sir,
I have made the README.md file updated & made it attractive & useful as I can .
Please take a review of my PR & please merge it under APERTRE'24

### CODE REVIEW

**Comment by apu52** [comment]
@darkard2003 Please merge it under APERTRE'24

**Comment by darkard2003** [comment]
The contribution stuff should not be here. Neither are all the git commands.

**Comment by apu52** [comment]
> The contribution stuff should not be here. Neither are all the git commands.

@darkard2003 I have removed the contributor part as well as the git commands . Now Please take a look sir

**Comment by apu52** [comment]
@darkard2003 I have removed the contributor part as well as the git commands . Now Please take a look sir

**Comment by apu52** [comment]
@darkard2003 Thank you for merging. but the  points regarding this PR will not be counted as the competition is already over yesterday. There is no need now to attach the labels now.
Thank you again!

**Pull request merged**
